Update reusable-build-test.yml

diff --git a/.github/workflows/reusable-build-test.yml b/.github/workflows/reusable-build-test.yml
--- a/.github/workflows/reusable-build-test.yml
+++ b/.github/workflows/reusable-build-test.yml
@@ -32,10 +32,12 @@ jobs:
 
       - name: Check if can run
         run: |
-          if [[ "${{ github.event.pull_request.labels }}" == *"Blocked: Build Fix Required"* ]]; then
-            echo "This PR has the 'Blocked: Build Fix Required' label, failing the action."
-            exit 1
-          fi
+          for label in "${{ toJson(github.event.pull_request.labels) }}"; do
+            if [[ "$label" == *"Blocked: Build Fix Required"* ]]; then
+              echo "This PR has the 'Blocked: Build Fix Required' label, failing the action."
+              exit 1
+            fi
+          done
 
       - name: Setup .NET
         uses: actions/setup-dotnet@v4
@@ -52,12 +54,10 @@ jobs:
       - name: Block PR if Build Fail
         if: failure() && github.event_name == 'pull_request'
         run: |
-          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
-          curl -X POST \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -H "Accept: application/vnd.github.v3+json" \
-            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels \
-            -d '{"labels":["Blocked: Build Fix Required"]}'
+          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'Blocked: Build Fix Required') }}" == "true" ]]; then
+            echo "This PR has the 'Blocked: Build Fix Required' label, failing the action."
+            exit 1
+          fi
             
        # 📝 Comment on PR when blocked
       - name: Comment on PR if Build Fail
@@ -80,7 +80,7 @@ jobs:
         
       - name: Check if can run
         run: |
-          if [[ "${{ github.event.pull_request.labels }}" == *"Blocked: Tests Fix Required"* ]]; then
+          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'Blocked: Tests Fix Required') }}" == "true" ]]; then
             echo "This PR has the 'Blocked: Tests Fix Required' label, failing the action."
             exit 1
           fi
